name: Bhavit
favicon: null
layout_spectrum: 0.32057
typography_spectrum: 0.37919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.6425290943589061
  saturation: 0.6414783166255802
  rhythmicContrast: 0.7768904406111687
purpose: []
